### ISSUE TITLE
No handlers could be found for logger "jsonselect.jsonselect"

### ISSUE THREAD

**Issue by paasar** [mwhooker/jsonselect#4]
Hi,

I got following message:
`No handlers could be found for logger "jsonselect.jsonselect"`

When running:
`python -m jsonselect itemId < file.json`

Adding the following to `jsonselect.py` helped:
`logging.basicConfig()`

And of course the problem does not happen when my command is correct and the program does not try to log anything:
`python -m jsonselect ".itemId" < file.json`

**Comment by mwhooker** [comment]
Thanks for catching this. Almost every logging method _except_ .exception calls logging.basicConfig.
