### ISSUE TITLE
:first-child does not behave like the demo

### ISSUE THREAD

**Issue by ProgVal** [mwhooker/jsonselect#5]
On the [demo website](http://jsonselect.org/#tryit) you can do `.drinkPreference :first-child` to get the first child, whatever its type (`"whiskey"`).

However, this implementation does not behave this way: unless a type is given, it does not return anything.

```
$ python -m jsonselect ".drinkPreference :first-child" conformance_tests/upstream/level_1/basic.json
$ python -m jsonselect ".drinkPreference string:first-child" conformance_tests/upstream/level_1/basic.json
"beer"
```

**Comment by ProgVal** [comment]
Update: I edited my initial message to make it clearer what the issue is

**Comment by mwhooker** [comment]
Dupe of #1
